-- 01_infrastructure.sql — Database, Schemas, Warehouse, Roles

DEFINE DATABASE HR_ANALYTICS_{{env}};

DEFINE SCHEMA HR_ANALYTICS_{{env}}.RAW;
DEFINE SCHEMA HR_ANALYTICS_{{env}}.CLEANSED;
DEFINE SCHEMA HR_ANALYTICS_{{env}}.ANALYTICS;
DEFINE SCHEMA HR_ANALYTICS_{{env}}.TESTS;

DEFINE WAREHOUSE HR_ANALYTICS_WH_{{env}}
    WAREHOUSE_SIZE = '{{wh_size}}'
    AUTO_SUSPEND = {{auto_suspend}}
    AUTO_RESUME = TRUE
    COMMENT = 'HR Analytics warehouse';

DEFINE ROLE HR_ANALYTICS_READER_{{env}};
DEFINE ROLE HR_ANALYTICS_WRITER_{{env}};
DEFINE ROLE HR_ANALYTICS_ADMIN_{{env}};

DEFINE DATABASE ROLE HR_ANALYTICS_{{env}}.DB_READER;
DEFINE DATABASE ROLE HR_ANALYTICS_{{env}}.DB_WRITER;
