-- 02_tables.sql — Bronze layer tables + internal stage

DEFINE TABLE HR_ANALYTICS_{{env}}.RAW.EMPLOYEES (
    EMP_ID       NUMBER(38,0) NOT NULL,
    FIRST_NAME   VARCHAR(100),
    LAST_NAME    VARCHAR(100),
    EMAIL        VARCHAR(255),
    DEPT_ID      NUMBER(38,0),
    HIRE_DATE    DATE,
    SALARY       NUMBER(12,2),
    CREATED_AT   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
DATA_RETENTION_TIME_IN_DAYS = {{data_retention_days}}
DATA_METRIC_SCHEDULE = 'TRIGGER_ON_CHANGES';

DEFINE TABLE HR_ANALYTICS_{{env}}.RAW.DEPARTMENTS (
    DEPT_ID    NUMBER(38,0) NOT NULL,
    DEPT_NAME  VARCHAR(100),
    LOCATION   VARCHAR(100),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
DATA_RETENTION_TIME_IN_DAYS = {{data_retention_days}}
DATA_METRIC_SCHEDULE = 'TRIGGER_ON_CHANGES';

DEFINE TABLE HR_ANALYTICS_{{env}}.RAW.PAYROLL (
    PAYROLL_ID  NUMBER(38,0) NOT NULL,
    EMP_ID      NUMBER(38,0) NOT NULL,
    PAY_PERIOD  DATE,
    GROSS_PAY   NUMBER(12,2),
    DEDUCTIONS  NUMBER(12,2),
    CREATED_AT  TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
DATA_RETENTION_TIME_IN_DAYS = {{data_retention_days}}
DATA_METRIC_SCHEDULE = 'TRIGGER_ON_CHANGES';

DEFINE TABLE HR_ANALYTICS_{{env}}.RAW.REVIEWS (
    REVIEW_ID   NUMBER(38,0) NOT NULL,
    EMP_ID      NUMBER(38,0) NOT NULL,
    REVIEW_DATE DATE,
    RATING      NUMBER(1,0),
    COMMENTS    VARCHAR(500),
    CREATED_AT  TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
DATA_RETENTION_TIME_IN_DAYS = {{data_retention_days}}
DATA_METRIC_SCHEDULE = 'TRIGGER_ON_CHANGES';

DEFINE STAGE HR_ANALYTICS_{{env}}.RAW.HR_LOAD_STAGE
    DIRECTORY = (ENABLE = TRUE)
    COMMENT = 'Stage for HR data file ingestion';
