-- 03_dynamic_tables.sql — Silver (cleansed) + Gold (analytics) layers

DEFINE DYNAMIC TABLE HR_ANALYTICS_{{env}}.CLEANSED.EMPLOYEES_CLEAN
    TARGET_LAG = '1 hour'
    WAREHOUSE = HR_ANALYTICS_WH_{{env}}
    REFRESH_MODE = AUTO
    INITIALIZE = ON_CREATE
AS
    SELECT
        EMP_ID,
        TRIM(UPPER(FIRST_NAME)) AS FIRST_NAME,
        TRIM(UPPER(LAST_NAME))  AS LAST_NAME,
        LOWER(TRIM(EMAIL))      AS EMAIL,
        DEPT_ID,
        HIRE_DATE,
        SALARY,
        CREATED_AT
    FROM HR_ANALYTICS_{{env}}.RAW.EMPLOYEES
    WHERE EMP_ID IS NOT NULL;

DEFINE DYNAMIC TABLE HR_ANALYTICS_{{env}}.CLEANSED.PAYROLL_CLEAN
    TARGET_LAG = '1 hour'
    WAREHOUSE = HR_ANALYTICS_WH_{{env}}
    REFRESH_MODE = AUTO
    INITIALIZE = ON_CREATE
AS
    SELECT
        PAYROLL_ID,
        EMP_ID,
        PAY_PERIOD,
        GROSS_PAY,
        DEDUCTIONS,
        GROSS_PAY - DEDUCTIONS AS NET_PAY,
        CREATED_AT
    FROM HR_ANALYTICS_{{env}}.RAW.PAYROLL
    WHERE PAYROLL_ID IS NOT NULL AND EMP_ID IS NOT NULL;

DEFINE DYNAMIC TABLE HR_ANALYTICS_{{env}}.ANALYTICS.DEPT_HEADCOUNT
    TARGET_LAG = '1 hour'
    WAREHOUSE = HR_ANALYTICS_WH_{{env}}
    REFRESH_MODE = AUTO
    INITIALIZE = ON_CREATE
AS
    SELECT
        d.DEPT_ID,
        UPPER(TRIM(d.DEPT_NAME)) AS DEPT_NAME,
        d.LOCATION,
        COUNT(e.EMP_ID)     AS HEADCOUNT,
        AVG(e.SALARY)       AS AVG_SALARY,
        MIN(e.HIRE_DATE)    AS EARLIEST_HIRE,
        MAX(e.HIRE_DATE)    AS LATEST_HIRE
    FROM HR_ANALYTICS_{{env}}.RAW.DEPARTMENTS d
    LEFT JOIN HR_ANALYTICS_{{env}}.CLEANSED.EMPLOYEES_CLEAN e
        ON d.DEPT_ID = e.DEPT_ID
    GROUP BY d.DEPT_ID, d.DEPT_NAME, d.LOCATION;

DEFINE DYNAMIC TABLE HR_ANALYTICS_{{env}}.ANALYTICS.PAYROLL_SUMMARY
    TARGET_LAG = '1 hour'
    WAREHOUSE = HR_ANALYTICS_WH_{{env}}
    REFRESH_MODE = AUTO
    INITIALIZE = ON_CREATE
AS
    SELECT
        d.DEPT_ID,
        UPPER(TRIM(d.DEPT_NAME)) AS DEPT_NAME,
        COUNT(DISTINCT p.EMP_ID) AS EMPLOYEE_COUNT,
        SUM(p.GROSS_PAY)         AS TOTAL_GROSS,
        SUM(p.DEDUCTIONS)        AS TOTAL_DEDUCTIONS,
        SUM(p.GROSS_PAY - p.DEDUCTIONS) AS TOTAL_NET
    FROM HR_ANALYTICS_{{env}}.CLEANSED.PAYROLL_CLEAN p
    JOIN HR_ANALYTICS_{{env}}.CLEANSED.EMPLOYEES_CLEAN e ON p.EMP_ID = e.EMP_ID
    JOIN HR_ANALYTICS_{{env}}.RAW.DEPARTMENTS d          ON e.DEPT_ID = d.DEPT_ID
    GROUP BY d.DEPT_ID, d.DEPT_NAME;
