-- 04_views.sql — Views & Secure Views

DEFINE VIEW HR_ANALYTICS_{{env}}.ANALYTICS.VW_ACTIVE_EMPLOYEES
AS
    SELECT e.*, d.DEPT_NAME
    FROM HR_ANALYTICS_{{env}}.CLEANSED.EMPLOYEES_CLEAN e
    JOIN HR_ANALYTICS_{{env}}.RAW.DEPARTMENTS d ON e.DEPT_ID = d.DEPT_ID;

DEFINE VIEW HR_ANALYTICS_{{env}}.ANALYTICS.VW_SALARY_BANDS
AS
    SELECT
        EMP_ID,
        FIRST_NAME,
        LAST_NAME,
        SALARY,
        HR_ANALYTICS_{{env}}.ANALYTICS.GET_PERFORMANCE_BAND(
          (SELECT r.RATING FROM HR_ANALYTICS_{{env}}.RAW.REVIEWS r WHERE r.EMP_ID = e.EMP_ID ORDER BY r.REVIEW_DATE DESC LIMIT 1)
        ) AS PERFORMANCE_BAND
    FROM HR_ANALYTICS_{{env}}.CLEANSED.EMPLOYEES_CLEAN e
    WHERE SALARY < HR_ANALYTICS_{{env}}.ANALYTICS.GET_MIN_SALARY_THRESHOLD();

DEFINE SECURE VIEW HR_ANALYTICS_{{env}}.ANALYTICS.VW_TOP_PERFORMERS
AS
    SELECT
        e.EMP_ID,
        e.FIRST_NAME,
        e.LAST_NAME,
        d.DEPT_NAME,
        r.RATING,
        HR_ANALYTICS_{{env}}.ANALYTICS.GET_PERFORMANCE_BAND(r.RATING) AS PERFORMANCE_BAND,
        e.SALARY,
        HR_ANALYTICS_{{env}}.ANALYTICS.FORMAT_SALARY(e.SALARY) AS SALARY_DISPLAY
    FROM HR_ANALYTICS_{{env}}.CLEANSED.EMPLOYEES_CLEAN e
    JOIN HR_ANALYTICS_{{env}}.RAW.REVIEWS r     ON e.EMP_ID = r.EMP_ID
    JOIN HR_ANALYTICS_{{env}}.RAW.DEPARTMENTS d ON e.DEPT_ID = d.DEPT_ID
    WHERE r.RATING >= 4
    ORDER BY r.RATING DESC, e.SALARY DESC;

DEFINE SECURE VIEW HR_ANALYTICS_{{env}}.ANALYTICS.VW_PAYROLL_OVERVIEW
AS
    SELECT
        DEPT_NAME,
        EMPLOYEE_COUNT,
        TOTAL_GROSS,
        TOTAL_DEDUCTIONS,
        TOTAL_NET
    FROM HR_ANALYTICS_{{env}}.ANALYTICS.PAYROLL_SUMMARY;
