-- 05_functions.sql — SQL Functions & User-Defined Data Metric Functions

DEFINE FUNCTION HR_ANALYTICS_{{env}}.ANALYTICS.GET_PERFORMANCE_BAND(RATING NUMBER)
    RETURNS VARCHAR
AS
$$
    CASE
        WHEN RATING = 5 THEN 'OUTSTANDING'
        WHEN RATING = 4 THEN 'EXCEEDS EXPECTATIONS'
        WHEN RATING = 3 THEN 'MEETS EXPECTATIONS'
        WHEN RATING = 2 THEN 'BELOW EXPECTATIONS'
        ELSE 'CRITICAL'
    END
$$;

DEFINE FUNCTION HR_ANALYTICS_{{env}}.ANALYTICS.GET_MIN_SALARY_THRESHOLD()
    RETURNS NUMBER
AS
$$
    100000
$$;

DEFINE FUNCTION HR_ANALYTICS_{{env}}.ANALYTICS.FORMAT_SALARY(AMOUNT NUMBER)
    RETURNS VARCHAR
AS
$$
    '$' || TO_VARCHAR(AMOUNT, '999,999,999.00')
$$;

DEFINE DATA METRIC FUNCTION HR_ANALYTICS_{{env}}.TESTS.SALARY_RANGE_CHECK(
    TABLE_NAME TABLE(
        COLUMN_VALUE NUMBER
    )
)
    RETURNS NUMBER
AS
$$
    SELECT COUNT(*)
    FROM TABLE_NAME
    WHERE COLUMN_VALUE IS NOT NULL
      AND (COLUMN_VALUE < 30000 OR COLUMN_VALUE > 500000)
$$;

DEFINE DATA METRIC FUNCTION HR_ANALYTICS_{{env}}.TESTS.EMAIL_FORMAT_CHECK(
    TABLE_NAME TABLE(
        COLUMN_VALUE VARCHAR
    )
)
    RETURNS NUMBER
AS
$$
    SELECT COUNT(*)
    FROM TABLE_NAME
    WHERE COLUMN_VALUE IS NOT NULL
      AND COLUMN_VALUE NOT RLIKE '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$'
$$;

DEFINE DATA METRIC FUNCTION HR_ANALYTICS_{{env}}.TESTS.RATING_RANGE_CHECK(
    TABLE_NAME TABLE(
        COLUMN_VALUE NUMBER
    )
)
    RETURNS NUMBER
AS
$$
    SELECT COUNT(*)
    FROM TABLE_NAME
    WHERE COLUMN_VALUE IS NOT NULL
      AND (COLUMN_VALUE < 1 OR COLUMN_VALUE > 5)
$$;
