-- 07_grants.sql — Role hierarchy, schema/object privileges

GRANT ROLE HR_ANALYTICS_READER_{{env}} TO ROLE HR_ANALYTICS_WRITER_{{env}};
GRANT ROLE HR_ANALYTICS_WRITER_{{env}} TO ROLE HR_ANALYTICS_ADMIN_{{env}};

GRANT DATABASE ROLE HR_ANALYTICS_{{env}}.DB_READER TO ROLE HR_ANALYTICS_READER_{{env}};
GRANT DATABASE ROLE HR_ANALYTICS_{{env}}.DB_WRITER TO ROLE HR_ANALYTICS_WRITER_{{env}};

GRANT USAGE ON DATABASE HR_ANALYTICS_{{env}} TO ROLE HR_ANALYTICS_READER_{{env}};
GRANT USAGE ON SCHEMA HR_ANALYTICS_{{env}}.RAW       TO ROLE HR_ANALYTICS_READER_{{env}};
GRANT USAGE ON SCHEMA HR_ANALYTICS_{{env}}.CLEANSED   TO ROLE HR_ANALYTICS_READER_{{env}};
GRANT USAGE ON SCHEMA HR_ANALYTICS_{{env}}.ANALYTICS  TO ROLE HR_ANALYTICS_READER_{{env}};

GRANT USAGE ON DATABASE HR_ANALYTICS_{{env}} TO ROLE HR_ANALYTICS_WRITER_{{env}};
GRANT USAGE ON SCHEMA HR_ANALYTICS_{{env}}.RAW TO ROLE HR_ANALYTICS_WRITER_{{env}};

GRANT USAGE ON DATABASE HR_ANALYTICS_{{env}} TO ROLE HR_ANALYTICS_ADMIN_{{env}};
GRANT USAGE ON SCHEMA HR_ANALYTICS_{{env}}.RAW       TO ROLE HR_ANALYTICS_ADMIN_{{env}};
GRANT USAGE ON SCHEMA HR_ANALYTICS_{{env}}.CLEANSED   TO ROLE HR_ANALYTICS_ADMIN_{{env}};
GRANT USAGE ON SCHEMA HR_ANALYTICS_{{env}}.ANALYTICS  TO ROLE HR_ANALYTICS_ADMIN_{{env}};
GRANT USAGE ON SCHEMA HR_ANALYTICS_{{env}}.TESTS      TO ROLE HR_ANALYTICS_ADMIN_{{env}};

GRANT SELECT ON TABLE HR_ANALYTICS_{{env}}.RAW.EMPLOYEES   TO ROLE HR_ANALYTICS_READER_{{env}};
GRANT SELECT ON TABLE HR_ANALYTICS_{{env}}.RAW.DEPARTMENTS TO ROLE HR_ANALYTICS_READER_{{env}};
GRANT SELECT ON TABLE HR_ANALYTICS_{{env}}.RAW.PAYROLL     TO ROLE HR_ANALYTICS_READER_{{env}};
GRANT SELECT ON TABLE HR_ANALYTICS_{{env}}.RAW.REVIEWS     TO ROLE HR_ANALYTICS_READER_{{env}};

GRANT INSERT, UPDATE ON TABLE HR_ANALYTICS_{{env}}.RAW.EMPLOYEES   TO ROLE HR_ANALYTICS_WRITER_{{env}};
GRANT INSERT, UPDATE ON TABLE HR_ANALYTICS_{{env}}.RAW.DEPARTMENTS TO ROLE HR_ANALYTICS_WRITER_{{env}};
GRANT INSERT, UPDATE ON TABLE HR_ANALYTICS_{{env}}.RAW.PAYROLL     TO ROLE HR_ANALYTICS_WRITER_{{env}};
GRANT INSERT, UPDATE ON TABLE HR_ANALYTICS_{{env}}.RAW.REVIEWS     TO ROLE HR_ANALYTICS_WRITER_{{env}};

GRANT SELECT ON DYNAMIC TABLE HR_ANALYTICS_{{env}}.CLEANSED.EMPLOYEES_CLEAN TO ROLE HR_ANALYTICS_READER_{{env}};
GRANT SELECT ON DYNAMIC TABLE HR_ANALYTICS_{{env}}.CLEANSED.PAYROLL_CLEAN   TO ROLE HR_ANALYTICS_READER_{{env}};
GRANT SELECT ON DYNAMIC TABLE HR_ANALYTICS_{{env}}.ANALYTICS.DEPT_HEADCOUNT  TO ROLE HR_ANALYTICS_READER_{{env}};
GRANT SELECT ON DYNAMIC TABLE HR_ANALYTICS_{{env}}.ANALYTICS.PAYROLL_SUMMARY TO ROLE HR_ANALYTICS_READER_{{env}};

GRANT SELECT ON VIEW HR_ANALYTICS_{{env}}.ANALYTICS.VW_ACTIVE_EMPLOYEES TO ROLE HR_ANALYTICS_READER_{{env}};
GRANT SELECT ON VIEW HR_ANALYTICS_{{env}}.ANALYTICS.VW_SALARY_BANDS     TO ROLE HR_ANALYTICS_READER_{{env}};
GRANT SELECT ON VIEW HR_ANALYTICS_{{env}}.ANALYTICS.VW_TOP_PERFORMERS   TO ROLE HR_ANALYTICS_READER_{{env}};
GRANT SELECT ON VIEW HR_ANALYTICS_{{env}}.ANALYTICS.VW_PAYROLL_OVERVIEW TO ROLE HR_ANALYTICS_READER_{{env}};

GRANT READ  ON STAGE HR_ANALYTICS_{{env}}.RAW.HR_LOAD_STAGE TO ROLE HR_ANALYTICS_WRITER_{{env}};
GRANT WRITE ON STAGE HR_ANALYTICS_{{env}}.RAW.HR_LOAD_STAGE TO ROLE HR_ANALYTICS_WRITER_{{env}};

GRANT USAGE ON WAREHOUSE HR_ANALYTICS_WH_{{env}} TO ROLE HR_ANALYTICS_READER_{{env}};
GRANT USAGE ON WAREHOUSE HR_ANALYTICS_WH_{{env}} TO ROLE HR_ANALYTICS_WRITER_{{env}};
GRANT USAGE ON WAREHOUSE HR_ANALYTICS_WH_{{env}} TO ROLE HR_ANALYTICS_ADMIN_{{env}};
