-- 08_data_quality.sql — ATTACH system & user DMFs with expectations

ATTACH DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT
    TO TABLE HR_ANALYTICS_{{env}}.RAW.EMPLOYEES
    ON (EMP_ID)
    EXPECTATION NO_NULL_EMP_IDS (VALUE = 0);

ATTACH DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT
    TO TABLE HR_ANALYTICS_{{env}}.RAW.EMPLOYEES
    ON (EMP_ID)
    EXPECTATION NO_DUPLICATE_EMP_IDS (VALUE = 0);

ATTACH DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT
    TO TABLE HR_ANALYTICS_{{env}}.RAW.EMPLOYEES
    ON (EMAIL)
    EXPECTATION NO_DUPLICATE_EMAILS (VALUE = 0);

ATTACH DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT
    TO TABLE HR_ANALYTICS_{{env}}.RAW.EMPLOYEES
    ON (EMAIL)
    EXPECTATION NO_NULL_EMAILS (VALUE = 0);

ATTACH DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT
    TO TABLE HR_ANALYTICS_{{env}}.RAW.DEPARTMENTS
    ON (DEPT_ID)
    EXPECTATION NO_NULL_DEPT_IDS (VALUE = 0);

ATTACH DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT
    TO TABLE HR_ANALYTICS_{{env}}.RAW.DEPARTMENTS
    ON (DEPT_ID)
    EXPECTATION NO_DUPLICATE_DEPT_IDS (VALUE = 0);

ATTACH DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT
    TO TABLE HR_ANALYTICS_{{env}}.RAW.PAYROLL
    ON (PAYROLL_ID)
    EXPECTATION NO_NULL_PAYROLL_IDS (VALUE = 0);

ATTACH DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT
    TO TABLE HR_ANALYTICS_{{env}}.RAW.REVIEWS
    ON (REVIEW_ID)
    EXPECTATION NO_NULL_REVIEW_IDS (VALUE = 0);

ATTACH DATA METRIC FUNCTION HR_ANALYTICS_{{env}}.TESTS.EMAIL_FORMAT_CHECK
    TO TABLE HR_ANALYTICS_{{env}}.RAW.EMPLOYEES
    ON (EMAIL)
    EXPECTATION ALL_EMAILS_VALID (VALUE = 0);

ATTACH DATA METRIC FUNCTION HR_ANALYTICS_{{env}}.TESTS.SALARY_RANGE_CHECK
    TO TABLE HR_ANALYTICS_{{env}}.RAW.EMPLOYEES
    ON (SALARY)
    EXPECTATION ALL_SALARIES_IN_RANGE (VALUE = 0);

ATTACH DATA METRIC FUNCTION HR_ANALYTICS_{{env}}.TESTS.RATING_RANGE_CHECK
    TO TABLE HR_ANALYTICS_{{env}}.RAW.REVIEWS
    ON (RATING)
    EXPECTATION ALL_RATINGS_1_TO_5 (VALUE = 0);
