-- 09_security.sql — Tags & Authentication Policies

DEFINE TAG HR_ANALYTICS_{{env}}.RAW.PII_LEVEL
    ALLOWED_VALUES 'HIGH', 'MEDIUM', 'LOW', 'NONE';

DEFINE TAG HR_ANALYTICS_{{env}}.RAW.COST_CENTER
    ALLOWED_VALUES 'ENGINEERING', 'MARKETING', 'FINANCE', 'HR', 'EXECUTIVE';

DEFINE TAG HR_ANALYTICS_{{env}}.RAW.DATA_DOMAIN
    ALLOWED_VALUES 'EMPLOYEE', 'PAYROLL', 'PERFORMANCE', 'DEPARTMENT';

DEFINE AUTHENTICATION POLICY HR_ANALYTICS_{{env}}.RAW.HR_MFA_POLICY
    AUTHENTICATION_METHODS = ('PASSWORD')
    MFA_ENROLLMENT = 'REQUIRED'
    CLIENT_TYPES = ('SNOWFLAKE_UI')
    SECURITY_INTEGRATIONS = ('ALL')
    COMMENT = 'MFA required for HR data access via UI';

DEFINE AUTHENTICATION POLICY HR_ANALYTICS_{{env}}.RAW.HR_SERVICE_POLICY
    AUTHENTICATION_METHODS = ('PASSWORD', 'KEYPAIR')
    CLIENT_TYPES = ('SNOWFLAKE_UI', 'DRIVERS')
    SECURITY_INTEGRATIONS = ('ALL')
    COMMENT = 'Auth policy for HR ETL service accounts';
